### ISSUE TITLE
Where can I find the original .tflite model?

### ISSUE THREAD

**Issue by jin-eld** [csarnataro/arduino-tinyml-plate-recognition#1]
Hi,

I see the repo contains the model which has already been converted for integration with Arduino; I'd like to try and use the model with a Coral Edge TPU, but as far as I understand, I need the original .tflite model which then needs to be converted for use with the Coral - is it available somewhere?

**Comment by csarnataro** [comment]
Hi,
maybe you can have a look at this folder
[library/eu-swiss-plate-recognition_inferencing/src/tflite-model](https://github.com/csarnataro/arduino-tinyml-plate-recognition/tree/main/library/eu-swiss-plate-recognition_inferencing/src/tflite-model)

**Comment by jin-eld** [comment]
Hi,

> Hi, maybe you can have a look at this folder [library/eu-swiss-plate-recognition_inferencing/src/tflite-model](https://github.com/csarnataro/arduino-tinyml-plate-recognition/tree/main/library/eu-swiss-plate-recognition_inferencing/src/tflite-model)

I saw this, but unless I am mistaken this is not the original model in `.tflite` format, but already a converted version for the Arduino in source code format? I am looking for the original model in tflite format which was used to generate the sources in that folder.

**Comment by csarnataro** [comment]
Hi, we created this model using Edge-Impulse. The project should be available as a public project here:
https://studio.edgeimpulse.com/public/377422/live

I see there are a few download options for tensorflow lite in the homepage (e.g. float32, int8...).
<img width="805" alt="image" src="https://github.com/user-attachments/assets/8a93368f-ae15-4ef7-b6e3-3906bda0a8da">

Let me know if one of these is what you were looking for.

**Comment by jin-eld** [comment]
> Hi, we created this model using Edge-Impulse. The project should be available as a public project here: https://studio.edgeimpulse.com/public/377422/live
> 
> I see there are a few download options for tensorflow lite in the homepage (e.g. float32, int8...).
...
> Let me know if one of these is what you were looking for.

Yes, thank you, this is exactly what I was looking for! The int8 version should in theory work on the Coral Edge TPU after processing it with the `edgetpu_compiler`, I'll give it a try tonight.

I now realize that the Edge-Impulse link has been on the front page all the time 🤦🏻‍♂️ Sorry for missing it :)
